<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOFY7k5U\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOFY7k5U/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerOFY7k5U.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerOFY7k5U\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerOFY7k5U\appAppKernelProdContainer([
    'container.build_hash' => 'OFY7k5U',
    'container.build_id' => '3941708f',
    'container.build_time' => 1762365393,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOFY7k5U');
