<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjSrC7Z\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjSrC7Z/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerAjSrC7Z.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerAjSrC7Z\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerAjSrC7Z\appAppKernelProdContainer([
    'container.build_hash' => 'AjSrC7Z',
    'container.build_id' => 'cd0e6417',
    'container.build_time' => 1761867807,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjSrC7Z');
