<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxquYJt\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxquYJt/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerVxquYJt.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerVxquYJt\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerVxquYJt\appAppKernelProdContainer([
    'container.build_hash' => 'VxquYJt',
    'container.build_id' => 'b207a63d',
    'container.build_time' => 1762279582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxquYJt');
